# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 41d62d4058fe05908c88ea785347b5d6296912deae9e7a1f617488fa1fd90388fa643c727d8b6747ecbb22d4bc14c1221f67fc19a49224a0cf90819acbf2363c

test:
  secret_key_base: 422aba2d8fc75899b64c4784c8e28c2e475d64a89139c653ebd66c84d804e1cb64e2832583ea0edad92b68a719395ea0d4ec669d56624f9f1d740bdf00c4f6c2

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
